language: python
python:
  - "3.5"
install:
  - pip3 install -U pip wheel setuptools
  - pip3 install coveralls --quiet
  - pip3 install cython --quiet
  - pip3 install -r requirements.txt --extra-index-url $PYPI_HOST_WITH_CRED --quiet

script: coverage run --source=. -m unittest discover -v

after_success:
    coveralls